spring:
  application:
    name: agenda-facil-pro

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50

  flyway:
    enabled: true
    locations: classpath:db/migration

api:
  security:
    token:
      access-token-expiration: 900000 # 15 min
      refresh-token-expiration: 604800000 # 7 dias